adesao/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from . import views


app_name = "adesao"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sucesso-cadastro-usuario/$',
        views.sucesso_usuario,
        name='sucesso_usuario'),
    url(r'^login/$', LoginView.as_view(template_name='index.html'),
        name='login'),
    url(r'^sair/$', LogoutView.as_view(template_name='index.html'),
        name='logout'),
    url(r'^ativar/usuario/(?P<codigo>[\w]+)/$',
        views.ativar_usuario, name='ativar_usuario'),


    url(r'^home/', views.home, name='home'),
    url(r'^usuario/$', views.CadastrarUsuario.as_view(), name='usuario'),
    url(r'^faleconosco/$', views.fale_conosco, name='faleconosco'),

    # Cadastro e alteração de prefeitura
    url(r'^municipio/selecionar$', views.selecionar_tipo_ente,
        name='selecionar_tipo_ente'),
    url(r'^sucesso-cadastro-prefeitura/$',
        views.sucesso_municipio,
        name='sucesso_municipio'),
    
    # Cadastro e alteração de responsável
    path('sucesso-cadastro-funcionario/',
        views.sucesso_funcionario,
        name='sucesso_funcionario'),
    path('funcionario/alterar/<int:pk>',
        login_required(views.AlterarFuncionario.as_view()),
        name='alterar_funcionario'),
    path('funcionario/<int:sistema>',
            login_required(views.CadastrarFuncionario.as_view()),
            name='cadastrar_funcionario'),
    path('sistema/cadastrar/',
            login_required(views.CadastrarSistemaCultura.as_view()),
            name='cadastrar_sistema'),
    path('sistema/alterar/<int:pk>',
            login_required(views.AlterarSistemaCultura.as_view()),
            name='alterar_sistema'),

    path('sistema',
            login_required(views.define_sistema_sessao),
            name='define_sistema_sessao'),

    # Minuta de acordo e termo de solicitação
    path('termo/<str:template>/<str:nome_arquivo>',
        login_required(views.GeraPDF.as_view()),
        name='gera_pdf'),

    # Consulta
    path('consultar/<str:tipo>', views.ConsultarEnte.as_view(), name='consultar'),
    path('detalhar/<int:cod_ibge>', views.Detalhar.as_view(), name='detalhar'),
    ]

planotrabalho/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'planotrabalho'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$',
        login_required(views.PlanoTrabalho.as_view()),
        name='planotrabalho'),

    path('componente/plano',
        login_required(views.CadastrarPlanoDeCultura.as_view()),
        name='cadastrar_plano'),
    path('componente/fundo_cultura',
        login_required(views.CadastrarFundoDeCultura.as_view()),
        name='cadastrar_fundo_cultura'),
    path('componente/orgao_gestor',
        login_required(views.CadastrarOrgaoGestor.as_view()),
        name='cadastrar_orgao'),
    path('componente/conselho',
        login_required(views.CadastrarConselhoDeCultura.as_view()),
        name='cadastrar_conselho'),
     path('componente/legislacao',
        login_required(views.CadastrarLegislacao.as_view()),
        name='cadastrar_legislacao'),
    path('componente/fundo/alterar/<int:pk>',
        login_required(views.AlterarFundoCultura.as_view()),
        name='alterar_fundo_cultura'),
    path('componente/orgao/alterar/<int:pk>',
        login_required(views.AlterarOrgaoGestor.as_view()),
        name='alterar_orgao'),
    path('componente/conselho/alterar/<int:pk>',
        login_required(views.AlterarConselhoCultura.as_view()),
        name='alterar_conselho'),
    path('componente/plano/alterar/<int:pk>',
        login_required(views.AlterarPlanoCultura.as_view()),
        name='alterar_plano'),
    path('componente/legislacao/alterar/<int:pk>',
        login_required(views.AlterarLegislacao.as_view()),
        name='alterar_legislacao'),

    url(r'^conselheiros/$',
        login_required(views.get_conselheiros),
        name='get_conselheiros'),
    path('<int:conselho>/conselheiro/criar',
        login_required(views.CriarConselheiro.as_view()),
        name="criar_conselheiro"),
    url(r'^conselheiro/listar/$',
        login_required(views.ListarConselheiros.as_view()),
        name="listar_conselheiros"),
    url(r'^conselheiro/editar/(?P<pk>[0-9]+)/$',
        login_required(views.AlterarConselheiro.as_view()),
        name="alterar_conselheiro"),
    url(r'^conselheiro/remover/(?P<pk>[0-9]+)/$',
        login_required(views.DesabilitarConselheiro.as_view()),
        name="remover_conselheiro"),
    ]

snc/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.urls import include, path

from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

from adesao import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^adesao/', include('adesao.urls', namespace="adesao")),

    url(r'^planotrabalho/',
        include('planotrabalho.urls', namespace="planotrabalho")),

    url(r'^gestao/', include('gestao.urls', namespace="gestao")),
    url(r'^admin/', admin.site.urls),

    url(r'^password_reset/$',
        PasswordResetView.as_view(),
        {'template_name': 'registration/password_reset_form.html'},
        name='password_reset'),

    url(r'^password_reset_done/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset_confirm/' +
        '(?P<uidb64>[0-9A-Za-z_\-]+)/' +
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),

    url(r'^password_reset_complete/$',
        PasswordResetCompleteView.as_view(),
        {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^mudar_senha/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha.html'},
        name='mudar_senha'),

    url(r'^mudar_senha_sucesso/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_concluido.html'},
        name='password_change_done'),

    url(r'^mudar_senha_gestao/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao.html',
         'post_change_redirect': 'password_change_done_gestao'},
        name='mudar_senha_gestao'),

    url(r'^mudar_senha_gestao_sucesso/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao_concluido.html'},
        name='password_change_done_gestao'),

    # url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^exportar/dados.csv', views.exportar_csv, name='exportar_csv'),
    url(r'^exportar/dados.ods', views.exportar_ods, name='exportar_ods'),
    url(r'^exportar/dados.xls', views.exportar_xls, name='exportar_xls'),

    # API URLS
    path('api/', include('apiv2.urls', namespace='api/')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

planotrabalho/models.py
import datetime

from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from django.contrib.contenttypes.fields import GenericRelation
from adesao.models import *

from simple_history.models import HistoricalRecords

from gestao.models import Diligencia

SITUACAO_CONSELHEIRO = (("1", "Habilitado"), ("0", "Desabilitado"))

LISTA_TIPOS_COMPONENTES = (
    (0, 'Lei Sistema'),
    (1, 'Órgão Gestor'),
    (2, 'Fundo Cultura'),
    (3, 'Conselho Cultural'),
    (4, 'Plano Cultura'),
)

LISTA_PERIODICIDADE = (
    (0, 'Anual (1 ano)'),
    (1, 'Bienal (2 anos)'),
    (2, 'Trienal (3 anos)'),
    (3, 'Quadrienal (4 anos)'),
    (4, 'Quinquenal (5 anos)'),
    (5, 'Hexanual (6 anos)'),
    (6, 'Decenal (10 anos)'),
    (7, 'Outra'),
)

LISTA_CURSOS = (
    (0, 'Oficina'),
    (1, 'Palestra'),
    (2, 'Seminário'),
    (3, 'Pós-Graduação'),
    (4, 'Especialização'),
    (5, 'Aperfeiçoamento'),
    (6, 'Extensão'),
)

LISTA_PERFIL_PARTICIPANTE_CURSOS = (
    (0, 'Gestor Público'),
    (1, 'Conselheiro de Cultura'),
    (2, 'Sociedade Civil'),
)

LISTA_SITUACAO_ARQUIVO = (
    (0, "Em preenchimento"),
    (1, "Avaliando anexo"),
    (2, "Concluída"),
    (3, "Arquivo aprovado com ressalvas"),
    (4, "Arquivo danificado"),
    (5, "Arquivo incompleto"),
    (6, "Arquivo incorreto"),
)

LISTA_PERFIS_ORGAO_GESTOR = (
    ('', "Selecione um perfil"),
    (0, "Não possui estrutura"),
    (1, "Órgão da administração indireta"),
    (2, "Secretaria em conjunto com outras políticas"),
    (3, "Secretaria exclusiva de cultura"),
    (4, "Setor subordinado à chefia do Executivo"),
    (5, "Setor subordinado à outra secretaria"),
)

LISTA_ESFERAS_FEDERACAO = (
    (0, "Nacional"),
    (1, "Estadual ou Distrital"),
    (2, "Municipal"),
)


def upload_to_componente(instance, filename):
    name = ''
    ext = slugify(filename.split('.').pop(-1))
    new_name = slugify(filename.rsplit('.', 1)[0])
    componente = instance._meta.object_name.lower()
    try:
        entefederado = instance.planotrabalho.usuario.municipio.id
        name = "{entefederado}/docs/{componente}/{new_name}.{ext}".format(
            entefederado=entefederado,
            componente=componente,
            new_name=new_name,
            ext=ext)
    except Exception:
        plano_id = instance.planotrabalho.id
        name = "sem_ente_federado/{plano_id}/docs/{componente}/{new_name}.{ext}".format(
                plano_id=plano_id,
                componente=componente,
                new_name=new_name,
                ext=ext)

    return name


def upload_to(instance, filename):
    componentes = {
            0: "legislacao",
            1: "orgao_gestor",
            2: "fundo_cultura",
            3: "conselho",
            4: "plano",
            }

    name = ""
    ext = slugify(filename.split(".").pop(-1))
    new_name = slugify(filename.rsplit(".", 1)[0])

    conselho = instance.conselhos.all().first()
    comprovante_cnpj = instance.comprovantes.all().first()
    metas = instance.metas_plano.all().first()
    anexo = instance.anexo_plano.all().first()

    if conselho:
        nome_componente = componentes.get(conselho.tipo)
    elif comprovante_cnpj:
        nome_componente = componentes.get(comprovante_cnpj.tipo)
    elif metas:
        nome_componente = componentes.get(metas.tipo)
    elif anexo:
        nome_componente = componentes.get(anexo.tipo)
    else:
        nome_componente = componentes.get(instance.tipo)

    name = f"docs/{nome_componente}/{instance.id}/{new_name}.{ext}"

    return name


class ArquivoComponente(models.Model):
    arquivo = models.FileField(upload_to=upload_to_componente, null=True, blank=True)
    situacao = models.ForeignKey('SituacoesArquivoPlano',
                                 on_delete=models.CASCADE,
                                 related_name='%(class)s_situacao',
                                 default=0)
    data_envio = models.DateField(default=datetime.date.today)

    class Meta:
        abstract = True


class ArquivoComponente2(models.Model):
    arquivo = models.FileField(upload_to=upload_to, null=True, blank=True)
    situacao = models.IntegerField(
        "Situação do Arquivo",
        choices=LISTA_SITUACAO_ARQUIVO,
        default=0,
    )
    diligencia = models.ForeignKey(
        'gestao.DiligenciaSimples',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='componente'
    )
    data_envio = models.DateField(default=datetime.date.today)
    data_publicacao = models.DateField(
        _("Data de Publicação do Arquivo do Componente"), null=True, blank=True)
    history = HistoricalRecords(inherit=True)


class Componente(ArquivoComponente2):
    tipo = models.IntegerField(
        choices=LISTA_TIPOS_COMPONENTES,
        default=0)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        url = reverse_lazy("gestao:detalhar", kwargs={"pk": self.sistema_cultura.pk})
        return url

    @property
    def nome_componente(self):
        return LISTA_TIPOS_COMPONENTES[self.tipo][1]


class OrgaoGestor2(Componente):
    perfil = models.IntegerField(
        choices=LISTA_PERFIS_ORGAO_GESTOR, null=True, blank=True)


class FundoDeCultura(Componente):
    cnpj = models.CharField(
        max_length=18,
        verbose_name='CNPJ',
        blank=True,
        null=True,
        default=None)
    comprovante_cnpj = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comprovantes')


class ConselhoDeCultura(Componente):
    lei = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='conselhos')
    exclusivo_cultura = models.BooleanField(blank=True, default=False)
    paritario = models.BooleanField(blank=True, default=False)


class PlanoDeCultura(Componente):
    metas = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='metas_plano')
    anexo = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='anexo_plano')
    anexo_na_lei = models.BooleanField(blank=True, default=False)
    metas_na_lei = models.BooleanField(blank=True, default=False)
    exclusivo_cultura = models.BooleanField(blank=True, default=False)
    ultimo_ano_vigencia = models.IntegerField(blank=True, null=True)
    periodicidade = models.CharField(blank=True, null=True, max_length=100)
    local_monitoramento = models.CharField(
        max_length=100,
        verbose_name='Local de Monitoramento',
        blank=True,
        null=True)
    ano_inicio_curso = models.IntegerField(blank=True, null=True)
    ano_termino_curso = models.IntegerField(blank=True, null=True)
    tipo_curso = models.IntegerField(
        "Tipo do Curso",
        choices=LISTA_CURSOS,
        blank=True,
        null=True
    )
    esfera_federacao_curso = ArrayField(models.CharField(max_length=1), size=3, blank=True,
        null=True)
    tipo_oficina = ArrayField(models.CharField(max_length=1), size=7, blank=True, null=True)
    perfil_participante = ArrayField(models.CharField(max_length=1), size=3, blank=True,
        null=True)



class PlanoTrabalho(models.Model):
    criacao_sistema = models.OneToOneField(
        "CriacaoSistema", on_delete=models.CASCADE, blank=True, null=True
    )
    orgao_gestor = models.OneToOneField(
        'OrgaoGestor',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    conselho_cultural = models.OneToOneField(
        'ConselhoCultural',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    fundo_cultura = models.OneToOneField(
        'FundoCultura',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    plano_cultura = models.OneToOneField(
        'PlanoCultura',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")

    def __str__(self):
        return str(self.id)


class CriacaoSistema(ArquivoComponente):
    minuta_projeto_lei = models.FileField(
        upload_to='minuta_lei',
        max_length=255,
        blank=True,
        null=True)
    lei_sistema_cultura = models.FileField(
        upload_to='leis_sistema_cultura',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class OrgaoGestor(ArquivoComponente):
    relatorio_atividade_secretaria = models.FileField(
        upload_to='relatorio_atividades',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class ConselhoCultural(ArquivoComponente):
    ata_regimento_aprovado = models.FileField(
        upload_to='regimentos',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class FundoCultura(ArquivoComponente):
    cnpj_fundo_cultura = models.CharField(
        max_length=18,
        verbose_name='CNPJ',
        blank=True,
        null=True,

snc/templates/confirmar_email.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div align="center">
    <h2>Email confirmado com sucesso</h2>
    <p>
      Para acessar o sistema vá para a página de login
    </p>
    <p>
      <a class="btn btn-success" href="{% url 'adesao:login' %}">Login</a>
    </p>
  </div>
</div>
{% endblock content %}

snc/templates/historico_mudancas.html
<br />
<table>
  <caption><h3>Histórico de Adesão</h3></caption>
  {% for historico in historico %}
  <tr>
    <td>Situação alterada para <strong>"{{ historico.get_situacao_display }}"</strong> em
    {{ historico.data_alteracao }}</td>
  </tr>
  {% endfor %}
</table>
<br />

snc/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" dir="ltr">

<head>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Sistema Nacional de Cultura</title>
  {% load static %}
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
  <link rel="apple-touch-icon" href="{% static 'img/touch_icon.png' %}">

  <!-- Plone CSS - only for preview, will be removed in rules.xml -->
  <link media="screen" href="{% static 'css/plone.css' %}" type="text/css" rel="stylesheet" id="plone-css">

  <!-- Theme CSS - only for preview, will be removed in rules and added in CSS registry -->
  <link media="all" href="{% static 'css/mainLogin.css' %}" type="text/css" rel="stylesheet" id="main-css">
  <link media="all" href="{% static 'css/styleLogin.css' %}" type="text/css" rel="stylesheet">

</head>

<body>
  <!-- BARRA DO GOVERNO FEDERAL -->
  <div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">
    <ul id="menu-barra-temp" style="list-style:none;">
      <li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>
      <li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>
    </ul>
  </div>


  <div id="wrapper">

    <!-- HEADER -->

    <div id="header" role="banner">

      <div>

        <ul id="accessibility">
          <li>
            <a accesskey="1" href="#acontent" id="link-conteudo">
                            Ir para o conteúdo
                            <span>1</span>
                        </a>
          </li>
          <li>
            <a accesskey="2" href="#anavigation" id="link-navegacao">
                            Ir para o menu
                            <span>2</span>
                        </a>
          </li>
          <li>
            <a accesskey="3" href="#SearchableText" id="link-buscar">
                            Ir para a busca
                            <span>3</span>
                        </a>
          </li>
          <li>
            <a accesskey="4" href="#afooter" id="link-rodape">
                            Ir para o rodapé
                            <span>4</span>
                        </a>
          </li>
        </ul>

        <ul id="language" class="hidden">
          <li class="language-es">
            <a href="#">Español</a>
          </li>
          <li class="language-en">
            <a href="#">English</a>
          </li>
        </ul>

        <ul id="portal-siteactions">
          <li>
            <a href="#">Acessibilidade</a>
          </li>
          <li>
            <a href="#">Alto Contraste</a>
          </li>
          <li>
            <a href="#">Mapa do Site</a>
          </li>
        </ul>

        <div id="logo">
          <a href="{% url 'adesao:index' %}" title="#">
            <span id="portal-title">Sistema Nacional de Cultura</span>
            <span id="portal-description" style="color:#FC0">Secretaria Especial da Cultura / Ministério da Cidadania</span>
          </a>

        </div>


        <br />
        <br />
        <br />
        <br />


        <div id="social-icons">
          <ul>
            <li id="portalredes-facebook" class="portalredes-item">
              <a href="https://www.facebook.com/pages/ArticulaMinc/1595363034014002" title="Facebook" target="_blank">
              </a>
            </li>
            <li id="portalredes-twitter" class="portalredes-item">
              <a href="https://twitter.com/ArticulaMINC" title="Twitter" target="_blank">
              </a>
            </li>
            <li id="portalredes-youtube" class="portalredes-item">
              <a href="https://www.youtube.com/channel/UC3cNjlfoG5jUV3sHcfhD9Vg" title="Youtube" target="_blank">
              </a>
            </li>
          </ul>
        </div>

      </div>
      <div id="sobre">
        <ul>
          <li id="link-sobre">
            <a href="http://portalsnc.cultura.gov.br/">Sobre o SNC</a>
          </li>
          |
          <li id="link-consulta">
            <a href="{% url 'adesao:consultar' tipo='municipio' %}">Consultar Informações</a>
          </li>
          |
          <li id="link-sobre">
            <a href="http://portalsnc.cultura.gov.br/perguntas-frequentes/" target="_blank">Perguntas frequentes</a>
          </li>
          |
          <li id="link-central">
            <a href="{% url 'adesao:faleconosco' %}">Fale conosco</a>
          </li>
        </ul>
      </div>
    </div>

    <!-- content -->

    <div id="main" role="main">
      <div id="plone-content">

        <!-- Demo Plone Content -->

        <div id="portal-columns" class="row">

          <div id="viewlet-above-content">



          </div>

          <!-- Column 1 -->
          <div id="navigation">
            <a name="anavigation" id="anavigation"></a>
            <span class="menuTrigger">Menu</span>

            <div id="portal-column-one" class="cell width-1:4 position-0">
              <div class="logo">
                <a href="{% url 'adesao:index' %}">
                  <img src="{% static 'img/logo-header.png' %}" alt="Sistema Nacional de Cultura" />
                </a>
              </div>
            </div>
          </div>

	 <section class="main">
            <form class="form-2" action="{% url 'adesao:login' %}" method="post">{% csrf_token %}
              {% if form.errors %}
                <p>Senha ou CPF incorretos.</p>
              {% endif %}
              <h1><span class="log-in">Acessar</span></h1>
              <p class="float">
                <label for="login" style="color:#FFF"><i class="icon-user"></i>CPF:</label>
                <input type="text" name="username" class="cpf" maxlength="14"/>
              </p>
              <p class="float">
                <label for="password" style="color:#FFF"><i class="icon-lock"></i>Senha:</label>
                <input type="password" name="password"/>
              </p>
              <p>
                <a href="{% url 'password_reset' %}" style="color:#FFF"><small>Esqueceu sua senha?</small></a>
              </p>
              <p class="clearfix">
                <a href="{% url 'adesao:usuario' %}" class="log-twitter">Novo Usuário</a>
                <input id="submit" type="submit" name="submit" value="Acessar" />
              </p>
            </form>
          </section>
          <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

          <!-- Conteudo -->
          <div id="portal-column-content" class="cell width-1:2 position-1:4">
            <a name="acontent" id="acontent"></a>
            <div id="viewlet-below-content"></div>

          </div>
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <!-- Column 2-->
        </div>

        <!-- /Demo Plone Content -->

      </div>

      <div class="clear"></div>
      <div id="voltar-topo">
        <a href="#wrapper">Voltar para o topo</a>
      </div>

    </div>

    <!-- Footer -->
    <div id="footer" role="contentinfo">
        <a name="afooter" id="afooter"></a>


        <div class="clear"></div>
        <div id="footer-brasil" class="footer-logos">
            <div>
                <a href="http://www.acessoainformacao.gov.br/" class="logo-acesso">
                    <img src="img/acesso-a-infornacao.png" alt="Acesso a Informa&ccedil;&atilde;o" />
                </a>
                <a href="http://www.brasil.gov.br/" class="logo-brasil">
                    <img src="img/brasil.png" alt="Brasil - Governo Federal" />
                </a>
            </div>
        </div>
    </div>

    <!-- /Footer-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.formatter.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/validaCPF.js' %}"></script>
    {% verbatim %}
    <script type="text/javascript">
      $(document).ready(function(){
        $(".cpf").formatter({
          'pattern': '{{999}}.{{999}}.{{999}}-{{99}}',
          'persistent': false,
        });

        $(".form-2").submit(function(){
          $(".cpf").formatter().resetPattern('{{99999999999}}')
        });
      });
    </script>
    {% endverbatim %}
    <!-- Script da Barra do Governo -->
    <script defer src="http://barra.brasil.gov.br/barra.js" type="text/javascript"></script>
</body>

</html>