adesao/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from . import views


app_name = "adesao"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sucesso-cadastro-usuario/$',
        views.sucesso_usuario,
        name='sucesso_usuario'),
    url(r'^login/$', LoginView.as_view(template_name='index.html'),
        name='login'),
    url(r'^sair/$', LogoutView.as_view(template_name='index.html'),
        name='logout'),
    url(r'^ativar/usuario/(?P<codigo>[\w]+)/$',
        views.ativar_usuario, name='ativar_usuario'),


    url(r'^home/', views.home, name='home'),
    url(r'^usuario/$', views.CadastrarUsuario.as_view(), name='usuario'),
    url(r'^faleconosco/$', views.fale_conosco, name='faleconosco'),

    # Cadastro e alteração de prefeitura
    url(r'^municipio/selecionar$', views.selecionar_tipo_ente,
        name='selecionar_tipo_ente'),
    url(r'^sucesso-cadastro-prefeitura/$',
        views.sucesso_municipio,
        name='sucesso_municipio'),
    
    # Cadastro e alteração de responsável
    path('sucesso-cadastro-funcionario/',
        views.sucesso_funcionario,
        name='sucesso_funcionario'),
    path('funcionario/alterar/<int:pk>',
        login_required(views.AlterarFuncionario.as_view()),
        name='alterar_funcionario'),
    path('funcionario/<int:sistema>',
            login_required(views.CadastrarFuncionario.as_view()),
            name='cadastrar_funcionario'),
    path('sistema/cadastrar/',
            login_required(views.CadastrarSistemaCultura.as_view()),
            name='cadastrar_sistema'),
    path('sistema/alterar/<int:pk>',
            login_required(views.AlterarSistemaCultura.as_view()),
            name='alterar_sistema'),

    path('sistema',
            login_required(views.define_sistema_sessao),
            name='define_sistema_sessao'),

    # Minuta de acordo e termo de solicitação
    path('termo/<str:template>/<str:nome_arquivo>',
        login_required(views.GeraPDF.as_view()),
        name='gera_pdf'),

    # Consulta
    path('consultar/<str:tipo>', views.ConsultarEnte.as_view(), name='consultar'),
    path('detalhar/<int:cod_ibge>', views.Detalhar.as_view(), name='detalhar'),
    ]

gestao/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.admin.views.decorators import staff_member_required

from . import views

app_name = 'gestao'

urlpatterns = [
    # Acompanhar andamento dos processos de adesão
    path('', staff_member_required(
        views.dashboard,
        login_url='adesao:login'), name='dashboard'),
    path('entes', staff_member_required(
        views.AcompanharSistemaCultura.as_view(),
        login_url='adesao:login'), name='acompanhar_adesao'),
    path('ente/<int:cod_ibge>/dados-adesao',
        staff_member_required(views.AlterarDadosEnte.as_view()),
        name='alterar_dados_adesao'),
    path('alterar/<int:pk>',
        staff_member_required(views.AlterarDadosSistemaCultura.as_view()),
        name='alterar_sistema'),
     path('alterar/funcionario/<int:pk>',
        staff_member_required(views.AlterarFuncionario.as_view()),
        name='alterar_funcionario'),
    path('funcionario/<int:sistema>',
        staff_member_required(views.CadastrarFuncionario.as_view()),
        name='cadastrar_funcionario'),

    # Rota para AlterarCadastrador
    path('ente/<int:cod_ibge>/alterarcadastrador',
        staff_member_required(views.AlterarCadastradorEnte.as_view()),
        name='alterar_cadastrador'),

    # Acompanhar e aditivar prazos dos municípios
    url(r'^acompanhar/prazo/',
        staff_member_required(views.AcompanharPrazo.as_view()), name='acompanhar_prazo'),
    url(r'^aditivar-prazo/',
        staff_member_required(views.aditivar_prazo, login_url='adesao:login'), name='aditivar_prazo'),

    # Acompanhar componentes
    path('plano-trabalho/',
            staff_member_required(views.plano_trabalho),
            name='plano_trabalho'),
    path('docs-componentes/',
            staff_member_required(views.listar_componentes),
            name='listar_componentes'),
    path('acompanhar/<str:componente>',
            staff_member_required(views.AcompanharComponente.as_view()),
            name='acompanhar_componente'),

    # Detalhar usuário
    path('ente/<int:cod_ibge>',
            staff_member_required(views.DetalharEnte.as_view()),
            name='detalhar'),
    # re_path(r'^detalhar/municipio/(?P<pk>[0-9]+)$',
    #     staff_member_required(views.DetalharEnte.as_view()),
    #     name='detalhar'),
    url(r'^usuarios/',
        staff_member_required(
            views.ListarUsuarios.as_view(),
            login_url='adesao:login'), name='usuarios'),
    url(r'^alterar/usuario/',
        staff_member_required(
            views.alterar_usuario,
            login_url='adesao:login'), name='alterar_usuario'),

    # UF e Município aninhados
    path("chain/ente",
        views.EnteChain.as_view(),
        name='ente_chain'),

    # Inserir de documentos de entes federados
    url(r'^inserir-documentos/ente-federado$',
        staff_member_required(views.ListarDocumentosEnteFederado.as_view()), name='inserir_entefederado'),
    path("inserir-documentos/ente-federado/alterar/<int:pk>",
        staff_member_required(views.AlterarDocumentosEnteFederado.as_view()), name='alterar_entefederado'),

    path("inserir-documentos/<str:componente>/<int:pk>", staff_member_required(
        views.InserirComponente.as_view(),
        login_url='adesao:login'), name='inserir_componente'),

    # Tela de alteração de upload do plano de trabalho
    path("inserir-documentos/plano/alterar/<int:pk>", staff_member_required(
        views.AlterarPlanoCultura.as_view(),
        login_url='adesao:login'), name='alterar_plano'),
    path("inserir-documentos/fundo_cultura/alterar/<int:pk>", staff_member_required(
        views.AlterarFundoCultura.as_view(),
        login_url='adesao:login'), name='alterar_fundo'),
    path("inserir-documentos/conselho/alterar/<int:pk>", staff_member_required(
        views.AlterarConselhoCultura.as_view(),
        login_url='adesao:login'), name='alterar_conselho'),
    path("inserir-documentos/orgao/alterar/<int:pk>", staff_member_required(
        views.AlterarOrgaoGestor.as_view(),
        login_url='adesao:login'), name='alterar_orgao'),
    path("inserir-documentos/<str:componente>/alterar/<int:pk>", staff_member_required(
        views.AlterarComponente.as_view(),
        login_url='adesao:login'), name='alterar_componente'),

    # ajax mudança de cadastrador
    url(r'^ajax_cadastrador_cpf$', staff_member_required(views.ajax_cadastrador_cpf), name='ajax_cadastrador_cpf'),


    # Diligência de Componente

    # url(r'^(?P<pk>[0-9]+)/diligencia/(?P<componente>[A-z]+)/(?P<resultado>[0-1])',
    #     staff_member_required(views.DiligenciaComponenteView.as_view()), name="diligencia_componente"),

    path("<int:pk>/diligencia/add",
        staff_member_required(views.DiligenciaGeralCreateView.as_view()),
        name="diligencia_geral_adicionar"),

    path("<int:pk>/diligencia/<str:componente>/<str:arquivo>",
        staff_member_required(views.DiligenciaComponenteView.as_view()),
        name="diligencia_componente"),

    path("<int:ente>/diligencia/<str:componente>/<str:arquivo>/<int:pk>",
         staff_member_required(
             views.AlterarDiligenciaComponenteView.as_view()),
        name="alterar_diligencia_componente"),

    path("<int:pk>/diligencia/<str:componente>/<int:pk_componente>/situacao",
        staff_member_required(views.SituacaoArquivoComponenteUpdateView.as_view()),
        name="componente_situacao_atualiza"),

    path("<int:pk>/diligencia",
        staff_member_required(views.DiligenciaGeralDetailView.as_view()),
        name="diligencia_geral"),

    path("<int:pk>/contato",
        staff_member_required(views.CriarContato.as_view()),
        name="criar_contato"),

    path("ajax/consultar_cpf",
            staff_member_required(views.ajax_consulta_cpf),
            name="ajax-consulta-cpf"),

    # ajax leaflet
    url(r'^ajax-consulta-entes$', staff_member_required(views.ajax_consulta_entes), name='ajax_consulta_entes'),

    # ajax datatable
    url(r'^datatable-entes$', staff_member_required(views.DataTableEntes.as_view()),
        name='ajax_entes'),
    url(r'^datatable-prazo$', staff_member_required(views.DataTablePrazo.as_view()),
        name='ajax_prazo'),
    url(r'^datatable-usuarios$', staff_member_required(views.DataTableUsuarios.as_view()),
        name='ajax_usuarios'),
    url(r'^datatable-plano-trabalho$', staff_member_required(views.DataTablePlanoTrabalho.as_view()),
        name='ajax_plano_trabalho'),
    url(r'^datatable-docs-componentes$', staff_member_required(views.DataTableListarDocumentos.as_view()),
        name='ajax_docs_componentes'),

    ]

snc/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.urls import include, path

from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

from adesao import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^adesao/', include('adesao.urls', namespace="adesao")),

    url(r'^planotrabalho/',
        include('planotrabalho.urls', namespace="planotrabalho")),

    url(r'^gestao/', include('gestao.urls', namespace="gestao")),
    url(r'^admin/', admin.site.urls),

    url(r'^password_reset/$',
        PasswordResetView.as_view(),
        {'template_name': 'registration/password_reset_form.html'},
        name='password_reset'),

    url(r'^password_reset_done/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset_confirm/' +
        '(?P<uidb64>[0-9A-Za-z_\-]+)/' +
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),

    url(r'^password_reset_complete/$',
        PasswordResetCompleteView.as_view(),
        {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^mudar_senha/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha.html'},
        name='mudar_senha'),

    url(r'^mudar_senha_sucesso/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_concluido.html'},
        name='password_change_done'),

    url(r'^mudar_senha_gestao/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao.html',
         'post_change_redirect': 'password_change_done_gestao'},
        name='mudar_senha_gestao'),

    url(r'^mudar_senha_gestao_sucesso/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao_concluido.html'},
        name='password_change_done_gestao'),

    # url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^exportar/dados.csv', views.exportar_csv, name='exportar_csv'),
    url(r'^exportar/dados.ods', views.exportar_ods, name='exportar_ods'),
    url(r'^exportar/dados.xls', views.exportar_xls, name='exportar_xls'),

    # API URLS
    path('api/', include('apiv2.urls', namespace='api/')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

gestao/models.py
import datetime

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from simple_history.models import HistoricalRecords
from adesao.middleware import get_current_user

TIPOS_DILIGENCIA = (
    ('geral', 'Geral'),
    ('componente', 'Específica'),)

LISTA_SITUACAO_ARQUIVO = (
    (0, "Em preenchimento"),
    (1, "Avaliando anexo"),
    (2, "Concluída"),
    (3, "Arquivo aprovado com ressalvas"),
    (4, "Arquivo danificado"),
    (5, "Arquivo incompleto"),
    (6, "Arquivo incorreto"),
)


class Diligencia(models.Model):
    texto_diligencia = models.TextField(max_length=200)
    classificacao_arquivo = models.IntegerField(choices=LISTA_SITUACAO_ARQUIVO,
                                                null=True, blank=True)
    data_criacao = models.DateField(default=datetime.date.today)
    # sistema_cultura = models.ForeignKey('adesao.SistemaCultura', on_delete=models.CASCADE,
                                        # null=True, blank=True)
    componente_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    componente_id = models.PositiveIntegerField()
    componente = GenericForeignKey('componente_type', 'componente_id')
    usuario = models.ForeignKey('adesao.Usuario', on_delete=models.CASCADE)
    tipo_diligencia = models.CharField(
            max_length=10,
            choices=TIPOS_DILIGENCIA)

    def __str__(self):
        return str(self.id)


class ArquivoHistoricalDiligenciaSimples(models.Model):
    arquivo_url = models.URLField(blank=True, null=True)

    class Meta:
        abstract = True


class DiligenciaSimples(models.Model):
    texto_diligencia = models.TextField(max_length=200)
    classificacao_arquivo = models.IntegerField(choices=LISTA_SITUACAO_ARQUIVO,
                                                null=True, blank=True)
    data_criacao = models.DateField(default=datetime.date.today)
    usuario = models.ForeignKey('adesao.Usuario', on_delete=models.CASCADE)
    history = HistoricalRecords(bases=[ArquivoHistoricalDiligenciaSimples, ])


class Contato(models.Model):
    contatado = models.CharField(max_length=100)
    contatante = models.ForeignKey("adesao.Usuario", on_delete=models.CASCADE, related_name="contatos")
    data = models.DateField()
    discussao = models.TextField()
    sistema_cultura = models.ForeignKey("adesao.SistemaCultura", on_delete=models.CASCADE, related_name="contatos")

    def save(self, *args, **kwargs):
        self.contatante = get_current_user()
        super().save(*args, **kwargs)

snc/forms.py
from django import forms
from django.template.defaultfilters import filesizeformat
from localflavor.br.forms import BRCNPJField
from snc.client import Client


class RestrictedFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        self.content_types = kwargs.pop("content_types")
        self.max_upload_size = kwargs.pop("max_upload_size")

        super(RestrictedFileField, self).__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        file = super(RestrictedFileField, self).clean(data, initial)

        try:
            content_type = file.content_type
            if content_type in self.content_types:
                if file._size > self.max_upload_size:
                    raise forms.ValidationError(
                        'O arquivo deve ter menos de %s. Tamanho atual %s'
                        % (filesizeformat(self.max_upload_size),
                            filesizeformat(file._size)))
            else:
                raise forms.ValidationError(
                    'Arquivos desse tipo não são aceitos.')
        except AttributeError:
            pass

        return data


class BRCNPJField(BRCNPJField):

    def clean(self, data):
        cnpj  = super(BRCNPJField, self).clean(data)

        if data:
            consulta = Client().consulta_cnpj(cnpj)

            if not consulta:
                raise forms.ValidationError('CNPJ Inválido')

        return data

snc/templates/gestao/base_gestao.html
{% load gestao_tags %}
<!DOCTYPE html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sistema Nacional de Cultura</title>


  {% load static %}

  <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}" />

  <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet">

  <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/material-icons.css' %}" />

  <link href="{% static 'css/font-awesome.min.css' %}?v=2.1.0" rel="stylesheet" type="text/css">
  <link href="{% static 'css/perfect-scrollbar-1.4.0.css' %}" rel="stylesheet" type="text/css" />

  <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet" type="text/css" />

  <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/material-dashboard-custom.css' %}" rel="stylesheet" type="text/css">

</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="green" data-background-color="black" data-image="{% static 'img/marca-dagua.png' %}">
      <div class="logo">
        <a href="/" class="simple-text logo-normal">
          SNC
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">

          <li class="nav-item" id="menu-inicio">
            <a class="nav-link" href="{% url 'gestao:dashboard' %}">
              <i class="material-icons">dashboard</i>
              <p>Inicio</p>
            </a>
          </li>

          <li class="nav-item" id="menu-usuarios">
            <a class="nav-link" href="{% url 'gestao:usuarios' %}">
              <i class="material-icons">person</i>
              <p>Usuarios</p>
            </a>
          </li>

          <li class="nav-item" id="menu-ente">
            <a class="nav-link" href="{% url 'gestao:acompanhar_adesao' %}">
              <i class="material-icons">place</i>
              <p>Ente Federado</p>
            </a>
          </li>

          <li class="nav-item" id="menu-prazo">
            <a class="nav-link" href="{% url 'gestao:acompanhar_prazo' %}">
              <i class="material-icons">hourglass_full</i>
              <p>Prazos</p>
            </a>
          </li>

          {% if request.user|has_group:"usuario_scdc" %}
          <li class="nav-item" id="menu-plano">
            <a class="nav-link" href="{% url 'gestao:plano_trabalho' %}">
              <i class="material-icons">location_ons</i>
              <p>Plano de Trabalho</p>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form" action="/gestao/entes" method="get">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" name="q" placeholder="Pesquisar ente">
                <button type="submit" class="btn btn-default btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item dropdown" title="Exportar">
                <a class="nav-link" href="javscript:void(0)" id="navbarDropdownMenuLink" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">save_alt</i>
                  <p class="d-lg-none d-md-block">
                    Exportar Planilha
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'exportar_xls' %}">XLS</a>
                  <a class="dropdown-item" href="{% url 'exportar_ods' %}">ODS</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="javscript:void(0)" id="navbarDropdownMenuLink" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  <span>
                    {{ request.user.usuario.nome_usuario |truncatewords:2 |slice:"-4" }}&nbsp;&nbsp;
                  </span>
                  <i class="material-icons">person</i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'mudar_senha_gestao' %}">Alterar Senha</a>
                  <a class="dropdown-item" href="{% url 'adesao:logout' %}">Sair</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <div id="errors">
            {% for field in form %}
            <div class="errors-field">
              <div class="label-tag">{{ field.label_tag }}</div>
              {{field.errors}}
            </div>
            {% endfor %}
            {% for field in form_gestor %}
            <div class="errors-field">
              <div class="label-tag">{{ field.label_tag }}</div>
              {{field.errors}}
            </div>
            {% endfor %}
            {% for field in form_sede %}
            <div class="errors-field">
              <div class="label-tag">{{ field.label_tag }}</div>
              {{field.errors}}
            </div>
            {% endfor %}
          </div>
          {% block content %}
          {% endblock content %}
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="http://portalsnc.cultura.gov.br">
                  Portal SNC
                </a>
              </li>
              <li>
                <a href="http://ver.snc.cultura.gov.br">
                  VerSNC
                </a>
              </li>
              <li>
                <a href="http://snc.cultura.gov.br/adesao/consultar/municipio">
                  Consulta Pública
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right" id="date">
            <i class="material-icons">favorite</i>
            Ministério da Cidadania - Secretaria Especial da Cultura
          </div>
        </div>
      </footer>
      <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
      </script>
    </div>
  </div>

  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-material-design.min.js' %}"></script>
  <script src="{% static 'js/chartist.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-notify.js' %}"></script>
  <script src="{% static 'js/material-dashboard.min.js' %}?v=2.1.0"></script>
  <script src="{% static 'js/jquery.mask.min.js' %}"></script>


  <script src="{% static 'js/jquery.dataTables-1.10.19.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

  <script src="{% static 'js/gijgo-1.9.11.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/messages.pt-br.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/dataTables.buttons-1.5.6.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/buttons.print-1.5.6.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/x-editable-1.5.3.min.js' %}" type="text/javascript"></script>
  <!-- <script src="https://pastebin.com/raw/qj6RxwEn" type="text/javascript"></script> -->
  <script src="{% static 'js/buttons.flash-1.5.6.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/jszip-3.1.3.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/pdfmake-0.1.53.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/vfs_fonts-0.1.53.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/buttons.html5-1.3.3.min.js' %}" type="text/javascript"></script>
  <!-- <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js" type="text/javascript"></script> -->
  <script src="{% static 'js/bootstrap-select-1.13.9.min.js' %}"></script>
  <script src="{% static 'js/card-input-file.js' %}"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>

  <script type="text/javascript">
    $(document).ready(function () {

      $('.errors-field').each((index, element) => {

        let field_name = '';
        let field_error = '';
        let field = $(element).children().text();

        field = field.split(":");
        field_name = field[0];
        field_error = field[1];

        if (field_error.length > 0) {
          let error_message = '<b>' + field_name + '</b> -  ' + field_error;

          $.notify(
            {
              icon: "error",
              message: error_message,
            },
            {
              type: "danger"
            }
          );
        }
      });

      let menu_target_active = $('menu').data('target');
      $('#menu-' + menu_target_active).addClass('active')

      {% verbatim %}

      $('.cnpj').mask('00.000.000/0000-00');
      $('.cep').mask('00000-000');
      $('.telefone').mask('(00)00000-0000');
      $('.cpf').mask('000.000.000-00');
      $('.date').mask('00/00/0000');

      $("form").submit(function () {
        $('.cnpj').unmask();
        $('.cep').unmask();
        $('.telefone').unmask();
        $('.cpf').unmask();
      });

      {% endverbatim %}

      md.initDashboardPageCharts();

      $('.date').each(function () {
        $(this).datepicker({
          showButtonPanel: true,
          locale: 'pt-br',
          format: 'dd/mm/yyyy'
        });
      });

    });
  </script>
  {% block js %}
  {% endblock js%}

</body>

</html>

snc/templates/gestao/inserir_documentacao.html
{% extends "gestao/base_gestao.html" %} {% load widget_tweaks %} {% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="card card-default">
            <div class="card-header card-plain card-header-primary">
                <h4 class="card-title">Componente</h4>
                <p class="card-category">Inserir componente do plano de trabalho</p>
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype=multipart/form-data>{% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <label>
                                Data de Publicação da Lei
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% render_field form.data_publicacao class="date" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% render_field form.arquivo %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <button type="submit" class="btn btn-primary pull-right">Salvar</button>
                            <a class="btn btn-secondary pull-right" href="{% url 'gestao:detalhar' cod_ibge=sistema.ente_federado.cod_ibge %}">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js%}

{% endblock js%}