planotrabalho/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'planotrabalho'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$',
        login_required(views.PlanoTrabalho.as_view()),
        name='planotrabalho'),

    path('componente/plano',
        login_required(views.CadastrarPlanoDeCultura.as_view()),
        name='cadastrar_plano'),
    path('componente/fundo_cultura',
        login_required(views.CadastrarFundoDeCultura.as_view()),
        name='cadastrar_fundo_cultura'),
    path('componente/orgao_gestor',
        login_required(views.CadastrarOrgaoGestor.as_view()),
        name='cadastrar_orgao'),
    path('componente/conselho',
        login_required(views.CadastrarConselhoDeCultura.as_view()),
        name='cadastrar_conselho'),
     path('componente/legislacao',
        login_required(views.CadastrarLegislacao.as_view()),
        name='cadastrar_legislacao'),
    path('componente/fundo/alterar/<int:pk>',
        login_required(views.AlterarFundoCultura.as_view()),
        name='alterar_fundo_cultura'),
    path('componente/orgao/alterar/<int:pk>',
        login_required(views.AlterarOrgaoGestor.as_view()),
        name='alterar_orgao'),
    path('componente/conselho/alterar/<int:pk>',
        login_required(views.AlterarConselhoCultura.as_view()),
        name='alterar_conselho'),
    path('componente/plano/alterar/<int:pk>',
        login_required(views.AlterarPlanoCultura.as_view()),
        name='alterar_plano'),
    path('componente/legislacao/alterar/<int:pk>',
        login_required(views.AlterarLegislacao.as_view()),
        name='alterar_legislacao'),

    url(r'^conselheiros/$',
        login_required(views.get_conselheiros),
        name='get_conselheiros'),
    path('<int:conselho>/conselheiro/criar',
        login_required(views.CriarConselheiro.as_view()),
        name="criar_conselheiro"),
    url(r'^conselheiro/listar/$',
        login_required(views.ListarConselheiros.as_view()),
        name="listar_conselheiros"),
    url(r'^conselheiro/editar/(?P<pk>[0-9]+)/$',
        login_required(views.AlterarConselheiro.as_view()),
        name="alterar_conselheiro"),
    url(r'^conselheiro/remover/(?P<pk>[0-9]+)/$',
        login_required(views.DesabilitarConselheiro.as_view()),
        name="remover_conselheiro"),
    ]

snc/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.urls import include, path

from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

from adesao import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^adesao/', include('adesao.urls', namespace="adesao")),

    url(r'^planotrabalho/',
        include('planotrabalho.urls', namespace="planotrabalho")),

    url(r'^gestao/', include('gestao.urls', namespace="gestao")),
    url(r'^admin/', admin.site.urls),

    url(r'^password_reset/$',
        PasswordResetView.as_view(),
        {'template_name': 'registration/password_reset_form.html'},
        name='password_reset'),

    url(r'^password_reset_done/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset_confirm/' +
        '(?P<uidb64>[0-9A-Za-z_\-]+)/' +
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),

    url(r'^password_reset_complete/$',
        PasswordResetCompleteView.as_view(),
        {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^mudar_senha/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha.html'},
        name='mudar_senha'),

    url(r'^mudar_senha_sucesso/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_concluido.html'},
        name='password_change_done'),

    url(r'^mudar_senha_gestao/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao.html',
         'post_change_redirect': 'password_change_done_gestao'},
        name='mudar_senha_gestao'),

    url(r'^mudar_senha_gestao_sucesso/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao_concluido.html'},
        name='password_change_done_gestao'),

    # url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^exportar/dados.csv', views.exportar_csv, name='exportar_csv'),
    url(r'^exportar/dados.ods', views.exportar_ods, name='exportar_ods'),
    url(r'^exportar/dados.xls', views.exportar_xls, name='exportar_xls'),

    # API URLS
    path('api/', include('apiv2.urls', namespace='api/')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

planotrabalho/models.py
import datetime

from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from django.contrib.contenttypes.fields import GenericRelation
from adesao.models import *

from simple_history.models import HistoricalRecords

from gestao.models import Diligencia

SITUACAO_CONSELHEIRO = (("1", "Habilitado"), ("0", "Desabilitado"))

LISTA_TIPOS_COMPONENTES = (
    (0, 'Lei Sistema'),
    (1, 'Órgão Gestor'),
    (2, 'Fundo Cultura'),
    (3, 'Conselho Cultural'),
    (4, 'Plano Cultura'),
)

LISTA_PERIODICIDADE = (
    (0, 'Anual (1 ano)'),
    (1, 'Bienal (2 anos)'),
    (2, 'Trienal (3 anos)'),
    (3, 'Quadrienal (4 anos)'),
    (4, 'Quinquenal (5 anos)'),
    (5, 'Hexanual (6 anos)'),
    (6, 'Decenal (10 anos)'),
    (7, 'Outra'),
)

LISTA_CURSOS = (
    (0, 'Oficina'),
    (1, 'Palestra'),
    (2, 'Seminário'),
    (3, 'Pós-Graduação'),
    (4, 'Especialização'),
    (5, 'Aperfeiçoamento'),
    (6, 'Extensão'),
)

LISTA_PERFIL_PARTICIPANTE_CURSOS = (
    (0, 'Gestor Público'),
    (1, 'Conselheiro de Cultura'),
    (2, 'Sociedade Civil'),
)

LISTA_SITUACAO_ARQUIVO = (
    (0, "Em preenchimento"),
    (1, "Avaliando anexo"),
    (2, "Concluída"),
    (3, "Arquivo aprovado com ressalvas"),
    (4, "Arquivo danificado"),
    (5, "Arquivo incompleto"),
    (6, "Arquivo incorreto"),
)

LISTA_PERFIS_ORGAO_GESTOR = (
    ('', "Selecione um perfil"),
    (0, "Não possui estrutura"),
    (1, "Órgão da administração indireta"),
    (2, "Secretaria em conjunto com outras políticas"),
    (3, "Secretaria exclusiva de cultura"),
    (4, "Setor subordinado à chefia do Executivo"),
    (5, "Setor subordinado à outra secretaria"),
)

LISTA_ESFERAS_FEDERACAO = (
    (0, "Nacional"),
    (1, "Estadual ou Distrital"),
    (2, "Municipal"),
)


def upload_to_componente(instance, filename):
    name = ''
    ext = slugify(filename.split('.').pop(-1))
    new_name = slugify(filename.rsplit('.', 1)[0])
    componente = instance._meta.object_name.lower()
    try:
        entefederado = instance.planotrabalho.usuario.municipio.id
        name = "{entefederado}/docs/{componente}/{new_name}.{ext}".format(
            entefederado=entefederado,
            componente=componente,
            new_name=new_name,
            ext=ext)
    except Exception:
        plano_id = instance.planotrabalho.id
        name = "sem_ente_federado/{plano_id}/docs/{componente}/{new_name}.{ext}".format(
                plano_id=plano_id,
                componente=componente,
                new_name=new_name,
                ext=ext)

    return name


def upload_to(instance, filename):
    componentes = {
            0: "legislacao",
            1: "orgao_gestor",
            2: "fundo_cultura",
            3: "conselho",
            4: "plano",
            }

    name = ""
    ext = slugify(filename.split(".").pop(-1))
    new_name = slugify(filename.rsplit(".", 1)[0])

    conselho = instance.conselhos.all().first()
    comprovante_cnpj = instance.comprovantes.all().first()
    metas = instance.metas_plano.all().first()
    anexo = instance.anexo_plano.all().first()

    if conselho:
        nome_componente = componentes.get(conselho.tipo)
    elif comprovante_cnpj:
        nome_componente = componentes.get(comprovante_cnpj.tipo)
    elif metas:
        nome_componente = componentes.get(metas.tipo)
    elif anexo:
        nome_componente = componentes.get(anexo.tipo)
    else:
        nome_componente = componentes.get(instance.tipo)

    name = f"docs/{nome_componente}/{instance.id}/{new_name}.{ext}"

    return name


class ArquivoComponente(models.Model):
    arquivo = models.FileField(upload_to=upload_to_componente, null=True, blank=True)
    situacao = models.ForeignKey('SituacoesArquivoPlano',
                                 on_delete=models.CASCADE,
                                 related_name='%(class)s_situacao',
                                 default=0)
    data_envio = models.DateField(default=datetime.date.today)

    class Meta:
        abstract = True


class ArquivoComponente2(models.Model):
    arquivo = models.FileField(upload_to=upload_to, null=True, blank=True)
    situacao = models.IntegerField(
        "Situação do Arquivo",
        choices=LISTA_SITUACAO_ARQUIVO,
        default=0,
    )
    diligencia = models.ForeignKey(
        'gestao.DiligenciaSimples',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='componente'
    )
    data_envio = models.DateField(default=datetime.date.today)
    data_publicacao = models.DateField(
        _("Data de Publicação do Arquivo do Componente"), null=True, blank=True)
    history = HistoricalRecords(inherit=True)


class Componente(ArquivoComponente2):
    tipo = models.IntegerField(
        choices=LISTA_TIPOS_COMPONENTES,
        default=0)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        url = reverse_lazy("gestao:detalhar", kwargs={"pk": self.sistema_cultura.pk})
        return url

    @property
    def nome_componente(self):
        return LISTA_TIPOS_COMPONENTES[self.tipo][1]


class OrgaoGestor2(Componente):
    perfil = models.IntegerField(
        choices=LISTA_PERFIS_ORGAO_GESTOR, null=True, blank=True)


class FundoDeCultura(Componente):
    cnpj = models.CharField(
        max_length=18,
        verbose_name='CNPJ',
        blank=True,
        null=True,
        default=None)
    comprovante_cnpj = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comprovantes')


class ConselhoDeCultura(Componente):
    lei = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='conselhos')
    exclusivo_cultura = models.BooleanField(blank=True, default=False)
    paritario = models.BooleanField(blank=True, default=False)


class PlanoDeCultura(Componente):
    metas = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='metas_plano')
    anexo = models.ForeignKey(
        'ArquivoComponente2',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='anexo_plano')
    anexo_na_lei = models.BooleanField(blank=True, default=False)
    metas_na_lei = models.BooleanField(blank=True, default=False)
    exclusivo_cultura = models.BooleanField(blank=True, default=False)
    ultimo_ano_vigencia = models.IntegerField(blank=True, null=True)
    periodicidade = models.CharField(blank=True, null=True, max_length=100)
    local_monitoramento = models.CharField(
        max_length=100,
        verbose_name='Local de Monitoramento',
        blank=True,
        null=True)
    ano_inicio_curso = models.IntegerField(blank=True, null=True)
    ano_termino_curso = models.IntegerField(blank=True, null=True)
    tipo_curso = models.IntegerField(
        "Tipo do Curso",
        choices=LISTA_CURSOS,
        blank=True,
        null=True
    )
    esfera_federacao_curso = ArrayField(models.CharField(max_length=1), size=3, blank=True,
        null=True)
    tipo_oficina = ArrayField(models.CharField(max_length=1), size=7, blank=True, null=True)
    perfil_participante = ArrayField(models.CharField(max_length=1), size=3, blank=True,
        null=True)



class PlanoTrabalho(models.Model):
    criacao_sistema = models.OneToOneField(
        "CriacaoSistema", on_delete=models.CASCADE, blank=True, null=True
    )
    orgao_gestor = models.OneToOneField(
        'OrgaoGestor',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    conselho_cultural = models.OneToOneField(
        'ConselhoCultural',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    fundo_cultura = models.OneToOneField(
        'FundoCultura',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    plano_cultura = models.OneToOneField(
        'PlanoCultura',
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")

    def __str__(self):
        return str(self.id)


class CriacaoSistema(ArquivoComponente):
    minuta_projeto_lei = models.FileField(
        upload_to='minuta_lei',
        max_length=255,
        blank=True,
        null=True)
    lei_sistema_cultura = models.FileField(
        upload_to='leis_sistema_cultura',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class OrgaoGestor(ArquivoComponente):
    relatorio_atividade_secretaria = models.FileField(
        upload_to='relatorio_atividades',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class ConselhoCultural(ArquivoComponente):
    ata_regimento_aprovado = models.FileField(
        upload_to='regimentos',
        max_length=255,
        blank=True,
        null=True)
    data_publicacao = models.DateField(
        blank=True,
        null=True)
    diligencias = GenericRelation(Diligencia, content_type_field="componente_type",
                                  object_id_field="componente_id")


class FundoCultura(ArquivoComponente):
    cnpj_fundo_cultura = models.CharField(
        max_length=18,
        verbose_name='CNPJ',
        blank=True,
        null=True,

snc/forms.py
from django import forms
from django.template.defaultfilters import filesizeformat
from localflavor.br.forms import BRCNPJField
from snc.client import Client


class RestrictedFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        self.content_types = kwargs.pop("content_types")
        self.max_upload_size = kwargs.pop("max_upload_size")

        super(RestrictedFileField, self).__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        file = super(RestrictedFileField, self).clean(data, initial)

        try:
            content_type = file.content_type
            if content_type in self.content_types:
                if file._size > self.max_upload_size:
                    raise forms.ValidationError(
                        'O arquivo deve ter menos de %s. Tamanho atual %s'
                        % (filesizeformat(self.max_upload_size),
                            filesizeformat(file._size)))
            else:
                raise forms.ValidationError(
                    'Arquivos desse tipo não são aceitos.')
        except AttributeError:
            pass

        return data


class BRCNPJField(BRCNPJField):

    def clean(self, data):
        cnpj  = super(BRCNPJField, self).clean(data)

        if data:
            consulta = Client().consulta_cnpj(cnpj)

            if not consulta:
                raise forms.ValidationError('CNPJ Inválido')

        return data

snc/templates/planotrabalho/cadastrar_conselheiros.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

<form class="form-horizontal" method="post">
    {% csrf_token %}
    <h3>
      <strong>Cadastrar Conselheiro</strong>
    </h3>

    <div class="form-group">
      <div class="actions">
            <label class="col-sm-4 control-label">
                Nome
            </label>
            {% render_field form.nome class="form-control" placeholder="Nome Completo"%}
            {{ form.nome.errors }}
            <br>
            <label class="col-sm-4 control-label">
                Email
            </label>
            {% render_field form.email class="form-control" placeholder="Email"%}
            {{ form.email.errors }}
            <br>
            <label class="col-sm-4 control-label">
                Segmento
            </label>
            {% render_field form.segmento class="form-control segmento" %}
            {{ form.segmento.errors }}
        <input type="text" name="outros" placeholder="Digite aqui seu segmento" class="form-control" style="display: none;"/><br/>
      </div>
    </div>

    <input type="submit" class="btn btn-success" value="Salvar" />
</form>

<script type="text/javascript">
    $(".segmento").change(function(){
      if ($(this).val() === '21'){
        $(this).parent().children('[name=outros]').fadeIn();
      }else {
        $(this).parent().children('[name=outros]').fadeOut();
      }
    });
</script>

{% endblock content %}

snc/templates/planotrabalho/desabilitar_conselheiro.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div align="center">
        <h3>Tem certeza que deseja remover este conselheiro?</h3>
        <p>Esta ação não pode ser desfeita.</p>

        <a class="btn btn-default" href="{% url 'planotrabalho:listar_conselheiros'%}">Não</a>
        <input class="btn btn-success" type="submit" value="Sim">
    </div>
</form>

{% endblock content %}

snc/templates/planotrabalho/listar_conselheiros.html
{% extends "base.html" %}
{% load gestao_tags %}
{% csrf_token %}
{% block content %}



<div class="dataTable_wrapper">
  <table class="table table-striped table-bordered table-hover dt-responsive" id="dataTables-example">
      <div align="center">
          <h3>Lista de gerenciamento de conselheiros</h3>
      </div>
    {% if object_list%}
    <p align="center" >Passe o mouse em cima do nome para mais informações.</p>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Segmento</th>
        <th align="center" colspan="2">Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for conselheiro in object_list %}
        <tr class="odd gradeX">
            <td width="50%" ><a title-data="Email: {{conselheiro.email}}" class="tooltip" >{{conselheiro.nome}}</a></td>
            <td width="50%">{{ conselheiro.segmento }}</td>
            <td >
                <a href="{% url 'planotrabalho:alterar_conselheiro' conselheiro.id %}">
                    <button class="btn btn-success edit" type="button" data-toggle="tooltip" title="Editar">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                </a>
            </td>
            <td>
                <a href="{% url 'planotrabalho:remover_conselheiro' conselheiro.id %}" >
                    <button class="btn btn-warning" type="button" data-toggle="tooltip" title="Remover">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </a>
            </td>
        </tr>
      {% endfor %}
    </tbody>
    {% else %}
    <div align="center">
        <p>Nenhum dado cadastrado.</p>
    </div>
    {% endif%}
  </table>
  {% if is_paginated %}
  <div style="float:right;">
    {% if page_obj.has_previous %}
      <a class="page-link previous" href="?{% url_replace 'page' page_obj.previous_page_number %}">Anterior</a>
    {% endif %}
      <a>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</a>
    {% if page_obj.has_next %}
      <a class="page-link next" href="?{% url_replace 'page' page_obj.next_page_number %}">Próximo</a>
    {% endif %}
  </div>
  </div>
  {% endif %}
  <br>
  <a href="{% url 'planotrabalho:criar_conselheiro' conselho=request.session.sistema_cultura_selecionado.conselho %}">
      <button type="button" class="btn btn-info" id="add" data-toggle="tooltip" title="Adicionar novo">
          <i class="fa fa-plus"></i>
      </button>
  </a>
</div>


<style>

.tooltip{
    display: inline;
    position: relative;
}

.tooltip:hover:after{
    background: #333;
    background: rgba(0,0,0,.8);
    border-radius: 5px;
    bottom: 26px;
    color: #fff;
    content: attr(title-data);
    left: 20%;
    padding: 5px 15px;
    position: absolute;
    z-index: 98;
    width: 220px;
}

</style>

{% endblock content %}

snc/templates/planotrabalho/plano_trabalho.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>  Bem vindo ao Plano de Cultura  </h1>
  <p style="text-align: justify;">
    Você está no ambiente do Plano de Trabalho. Nesta fase, é preciso anexar as comprovações de execução de cada um dos componentes do sistema de cultura local (como leis, decretos e demais normativas), bem como a data de publicação de cada uma delas, nos campos específicos disponíveis nesta plataforma.
  </p>
  <p style="text-align: justify;">
    Tais arquivos serão validados pela equipe da Secretaria Especial da Cultura / Ministério da Cidadania responsável pelo SNC que enviará uma mensagem após conclusão do procedimento, para o e-mail cadastrado pelo ente federado (estado/município). É importante manter suas informações sempre atualizadas.
  </p>
  <p style="text-align: justify;">
    OBS: Conforme Acordo de Cooperação Federativa assinado, o ente federado compromete-se a cumprir com o Plano de Trabalho em até dois anos contados da data de publicação do referido Acordo no Diário Oficial da União (DOU). Caso o prazo não seja cumprido, é necessário que o ente federado envie um Oficio assinado pelo Governador – Estado ou Prefeito – Município, solicitando prorrogação por mais dois anos para o e-mail <strong>snc@cultura.gov.br</strong>. Vide tutorial <a href="http://portalsnc.cultura.gov.br/wp-content/uploads/sites/32/2019/02/MODELO-DE-OF%C3%8DCIO-PARA-PRORROGA%C3%87%C3%83O-DE-PRAZO-DO-PLANO-DE-TRABALHO-2019.pdf">“Ofício de Prazo do Plano de Trabalho”</a>
  </p>

  <ul class="list-group">

    <li class="list-group-item">
      <p>
        <strong>I. Lei de Criação do Sistema de Cultura</strong>
      </p>
      {% if not sistema.legislacao.arquivo %}
        <a class="btn btn-success" style="color:#FFF" href="{% url 'planotrabalho:cadastrar_legislacao' %}" >Enviar Comprovação</a>
        </br>
        </br>
      {% else %}
        <strong>Situação da Lei: </strong>{{ sistema.legislacao.get_situacao_display|default:"Não possui" }}</br>
        <br />
        <a class="btn btn-warning" style="color:#FFF" href="{% url 'planotrabalho:alterar_legislacao' pk=sistema.legislacao.id %}">Editar Componente</a>
        <br />
        </br>
      {% endif %}
    </li>
    <li class="list-group-item">
      <p>
        <strong>II. Órgão Gestor</strong>
      </p>
      {% if not sistema.orgao_gestor.arquivo %}
        <a class="btn btn-success" style="color:#FFF" href="{% url 'planotrabalho:cadastrar_orgao' %}" >Enviar Comprovação</a>
        </br>
        </br>
      {% else %}
        <strong>Situação da Lei: </strong>{{ sistema.orgao_gestor.get_situacao_display|default:"Não possui" }}</br>
        <br />
        <a class="btn btn-warning" style="color:#FFF" href="{% url 'planotrabalho:alterar_orgao' pk=sistema.orgao_gestor.id %}">Editar Componente</a>
        <br />
        </br>
      {% endif %}
    </li>
    <li class="list-group-item">
      <p>
        <strong>III. Conselho de Política Cultural</strong>
      </p>
      {% if not sistema.conselho.arquivo and not sistema.conselho.lei %}
        <a class="btn btn-success" style="color:#FFF" href="{% url 'planotrabalho:cadastrar_conselho' %}" >Enviar Comprovação</a>
        </br>
        </br>
      {% else %}
        <strong>Situação da Lei: </strong>{{ sistema.conselho.lei.get_situacao_display|default:"Não possui" }}</br>
        <strong>Situação da Ata: </strong>{{ sistema.conselho.get_situacao_display|default:"Não possui"}}</br>
        </br>
        <a class="btn btn-warning" style="color:#FFF" href="{% url 'planotrabalho:alterar_conselho' pk=sistema.conselho.id %}">Editar Componente</a>
        </br>
        </br>
      {% endif %}
    </li>
    <li class="list-group-item">
      <p>
        <strong>IV. Fundo de Cultura</strong>
      </p>
      {% if not sistema.fundo_cultura.arquivo and not sistema.fundo_cultura.comprovante_cnpj %}
        <a class="btn btn-success" style="color:#FFF" href="{% url 'planotrabalho:cadastrar_fundo_cultura' %}" >Enviar Comprovação</a>
        </br>
        </br>
      {% else %}
        <strong>Situação da Lei: </strong>{{ sistema.fundo_cultura.get_situacao_display|default:"Não possui" }}</br>
        <strong>Situação do Comprovante do CNPJ: </strong>{{ sistema.fundo_cultura.comprovante_cnpj.get_situacao_display|default:"Não possui"}}</br>
        </br>
        <a class="btn btn-warning" style="color:#FFF" href="{% url 'planotrabalho:alterar_fundo_cultura' pk=sistema.fundo_cultura.id %}">Editar Componente</a>
        </br>
        </br>
      {% endif %}
    </li>
    <li class="list-group-item">
      <p>
        <strong>V. Plano de Cultura</strong>
      </p>
      {% if not sistema.plano.situacao and not sistema.plano.anexo and not sistema.plano.metas %}
        <a class="btn btn-success" style="color:#FFF" href="{% url 'planotrabalho:cadastrar_plano' %}" >Enviar Comprovação</a>
        </br>
        </br>
      {% else %}
        <strong>Situação da Lei: </strong>{{ sistema.plano.get_situacao_display|default:"Não possui" }}</br>
        <strong>Situação do Anexo da Lei: </strong>{{ sistema.plano.anexo.get_situacao_display|default:"Não possui"}}</br>
        <strong>Situação do Arquivo com as Metas: </strong>{{ sistema.plano.metas.get_situacao_display|default:"Não possui"}}</br>
        </br>
        <a class="btn btn-warning" style="color:#FFF" href="{% url 'planotrabalho:alterar_plano' pk=sistema.plano.id %}">Editar Componente</a>
      </br>
      {% endif %}
    </li>

  </ul>
{% endblock content %}