gestao/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.contrib.admin.views.decorators import staff_member_required

from . import views

app_name = 'gestao'

urlpatterns = [
    # Acompanhar andamento dos processos de adesão
    path('', staff_member_required(
        views.dashboard,
        login_url='adesao:login'), name='dashboard'),
    path('entes', staff_member_required(
        views.AcompanharSistemaCultura.as_view(),
        login_url='adesao:login'), name='acompanhar_adesao'),
    path('ente/<int:cod_ibge>/dados-adesao',
        staff_member_required(views.AlterarDadosEnte.as_view()),
        name='alterar_dados_adesao'),
    path('alterar/<int:pk>',
        staff_member_required(views.AlterarDadosSistemaCultura.as_view()),
        name='alterar_sistema'),
     path('alterar/funcionario/<int:pk>',
        staff_member_required(views.AlterarFuncionario.as_view()),
        name='alterar_funcionario'),
    path('funcionario/<int:sistema>',
        staff_member_required(views.CadastrarFuncionario.as_view()),
        name='cadastrar_funcionario'),

    # Rota para AlterarCadastrador
    path('ente/<int:cod_ibge>/alterarcadastrador',
        staff_member_required(views.AlterarCadastradorEnte.as_view()),
        name='alterar_cadastrador'),

    # Acompanhar e aditivar prazos dos municípios
    url(r'^acompanhar/prazo/',
        staff_member_required(views.AcompanharPrazo.as_view()), name='acompanhar_prazo'),
    url(r'^aditivar-prazo/',
        staff_member_required(views.aditivar_prazo, login_url='adesao:login'), name='aditivar_prazo'),

    # Acompanhar componentes
    path('plano-trabalho/',
            staff_member_required(views.plano_trabalho),
            name='plano_trabalho'),
    path('docs-componentes/',
            staff_member_required(views.listar_componentes),
            name='listar_componentes'),
    path('acompanhar/<str:componente>',
            staff_member_required(views.AcompanharComponente.as_view()),
            name='acompanhar_componente'),

    # Detalhar usuário
    path('ente/<int:cod_ibge>',
            staff_member_required(views.DetalharEnte.as_view()),
            name='detalhar'),
    # re_path(r'^detalhar/municipio/(?P<pk>[0-9]+)$',
    #     staff_member_required(views.DetalharEnte.as_view()),
    #     name='detalhar'),
    url(r'^usuarios/',
        staff_member_required(
            views.ListarUsuarios.as_view(),
            login_url='adesao:login'), name='usuarios'),
    url(r'^alterar/usuario/',
        staff_member_required(
            views.alterar_usuario,
            login_url='adesao:login'), name='alterar_usuario'),

    # UF e Município aninhados
    path("chain/ente",
        views.EnteChain.as_view(),
        name='ente_chain'),

    # Inserir de documentos de entes federados
    url(r'^inserir-documentos/ente-federado$',
        staff_member_required(views.ListarDocumentosEnteFederado.as_view()), name='inserir_entefederado'),
    path("inserir-documentos/ente-federado/alterar/<int:pk>",
        staff_member_required(views.AlterarDocumentosEnteFederado.as_view()), name='alterar_entefederado'),

    path("inserir-documentos/<str:componente>/<int:pk>", staff_member_required(
        views.InserirComponente.as_view(),
        login_url='adesao:login'), name='inserir_componente'),

    # Tela de alteração de upload do plano de trabalho
    path("inserir-documentos/plano/alterar/<int:pk>", staff_member_required(
        views.AlterarPlanoCultura.as_view(),
        login_url='adesao:login'), name='alterar_plano'),
    path("inserir-documentos/fundo_cultura/alterar/<int:pk>", staff_member_required(
        views.AlterarFundoCultura.as_view(),
        login_url='adesao:login'), name='alterar_fundo'),
    path("inserir-documentos/conselho/alterar/<int:pk>", staff_member_required(
        views.AlterarConselhoCultura.as_view(),
        login_url='adesao:login'), name='alterar_conselho'),
    path("inserir-documentos/orgao/alterar/<int:pk>", staff_member_required(
        views.AlterarOrgaoGestor.as_view(),
        login_url='adesao:login'), name='alterar_orgao'),
    path("inserir-documentos/<str:componente>/alterar/<int:pk>", staff_member_required(
        views.AlterarComponente.as_view(),
        login_url='adesao:login'), name='alterar_componente'),

    # ajax mudança de cadastrador
    url(r'^ajax_cadastrador_cpf$', staff_member_required(views.ajax_cadastrador_cpf), name='ajax_cadastrador_cpf'),


    # Diligência de Componente

    # url(r'^(?P<pk>[0-9]+)/diligencia/(?P<componente>[A-z]+)/(?P<resultado>[0-1])',
    #     staff_member_required(views.DiligenciaComponenteView.as_view()), name="diligencia_componente"),

    path("<int:pk>/diligencia/add",
        staff_member_required(views.DiligenciaGeralCreateView.as_view()),
        name="diligencia_geral_adicionar"),

    path("<int:pk>/diligencia/<str:componente>/<str:arquivo>",
        staff_member_required(views.DiligenciaComponenteView.as_view()),
        name="diligencia_componente"),

    path("<int:ente>/diligencia/<str:componente>/<str:arquivo>/<int:pk>",
         staff_member_required(
             views.AlterarDiligenciaComponenteView.as_view()),
        name="alterar_diligencia_componente"),

    path("<int:pk>/diligencia/<str:componente>/<int:pk_componente>/situacao",
        staff_member_required(views.SituacaoArquivoComponenteUpdateView.as_view()),
        name="componente_situacao_atualiza"),

    path("<int:pk>/diligencia",
        staff_member_required(views.DiligenciaGeralDetailView.as_view()),
        name="diligencia_geral"),

    path("<int:pk>/contato",
        staff_member_required(views.CriarContato.as_view()),
        name="criar_contato"),

    path("ajax/consultar_cpf",
            staff_member_required(views.ajax_consulta_cpf),
            name="ajax-consulta-cpf"),

    # ajax leaflet
    url(r'^ajax-consulta-entes$', staff_member_required(views.ajax_consulta_entes), name='ajax_consulta_entes'),

    # ajax datatable
    url(r'^datatable-entes$', staff_member_required(views.DataTableEntes.as_view()),
        name='ajax_entes'),
    url(r'^datatable-prazo$', staff_member_required(views.DataTablePrazo.as_view()),
        name='ajax_prazo'),
    url(r'^datatable-usuarios$', staff_member_required(views.DataTableUsuarios.as_view()),
        name='ajax_usuarios'),
    url(r'^datatable-plano-trabalho$', staff_member_required(views.DataTablePlanoTrabalho.as_view()),
        name='ajax_plano_trabalho'),
    url(r'^datatable-docs-componentes$', staff_member_required(views.DataTableListarDocumentos.as_view()),
        name='ajax_docs_componentes'),

    ]

snc/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.urls import include, path

from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

from adesao import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^adesao/', include('adesao.urls', namespace="adesao")),

    url(r'^planotrabalho/',
        include('planotrabalho.urls', namespace="planotrabalho")),

    url(r'^gestao/', include('gestao.urls', namespace="gestao")),
    url(r'^admin/', admin.site.urls),

    url(r'^password_reset/$',
        PasswordResetView.as_view(),
        {'template_name': 'registration/password_reset_form.html'},
        name='password_reset'),

    url(r'^password_reset_done/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset_confirm/' +
        '(?P<uidb64>[0-9A-Za-z_\-]+)/' +
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),

    url(r'^password_reset_complete/$',
        PasswordResetCompleteView.as_view(),
        {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^mudar_senha/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha.html'},
        name='mudar_senha'),

    url(r'^mudar_senha_sucesso/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_concluido.html'},
        name='password_change_done'),

    url(r'^mudar_senha_gestao/$',
        PasswordChangeView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao.html',
         'post_change_redirect': 'password_change_done_gestao'},
        name='mudar_senha_gestao'),

    url(r'^mudar_senha_gestao_sucesso/$',
        PasswordResetDoneView.as_view(),
        {'template_name': 'registration/mudar_senha_gestao_concluido.html'},
        name='password_change_done_gestao'),

    # url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^exportar/dados.csv', views.exportar_csv, name='exportar_csv'),
    url(r'^exportar/dados.ods', views.exportar_ods, name='exportar_ods'),
    url(r'^exportar/dados.xls', views.exportar_xls, name='exportar_xls'),

    # API URLS
    path('api/', include('apiv2.urls', namespace='api/')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

gestao/models.py
import datetime

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from simple_history.models import HistoricalRecords
from adesao.middleware import get_current_user

TIPOS_DILIGENCIA = (
    ('geral', 'Geral'),
    ('componente', 'Específica'),)

LISTA_SITUACAO_ARQUIVO = (
    (0, "Em preenchimento"),
    (1, "Avaliando anexo"),
    (2, "Concluída"),
    (3, "Arquivo aprovado com ressalvas"),
    (4, "Arquivo danificado"),
    (5, "Arquivo incompleto"),
    (6, "Arquivo incorreto"),
)


class Diligencia(models.Model):
    texto_diligencia = models.TextField(max_length=200)
    classificacao_arquivo = models.IntegerField(choices=LISTA_SITUACAO_ARQUIVO,
                                                null=True, blank=True)
    data_criacao = models.DateField(default=datetime.date.today)
    # sistema_cultura = models.ForeignKey('adesao.SistemaCultura', on_delete=models.CASCADE,
                                        # null=True, blank=True)
    componente_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    componente_id = models.PositiveIntegerField()
    componente = GenericForeignKey('componente_type', 'componente_id')
    usuario = models.ForeignKey('adesao.Usuario', on_delete=models.CASCADE)
    tipo_diligencia = models.CharField(
            max_length=10,
            choices=TIPOS_DILIGENCIA)

    def __str__(self):
        return str(self.id)


class ArquivoHistoricalDiligenciaSimples(models.Model):
    arquivo_url = models.URLField(blank=True, null=True)

    class Meta:
        abstract = True


class DiligenciaSimples(models.Model):
    texto_diligencia = models.TextField(max_length=200)
    classificacao_arquivo = models.IntegerField(choices=LISTA_SITUACAO_ARQUIVO,
                                                null=True, blank=True)
    data_criacao = models.DateField(default=datetime.date.today)
    usuario = models.ForeignKey('adesao.Usuario', on_delete=models.CASCADE)
    history = HistoricalRecords(bases=[ArquivoHistoricalDiligenciaSimples, ])


class Contato(models.Model):
    contatado = models.CharField(max_length=100)
    contatante = models.ForeignKey("adesao.Usuario", on_delete=models.CASCADE, related_name="contatos")
    data = models.DateField()
    discussao = models.TextField()
    sistema_cultura = models.ForeignKey("adesao.SistemaCultura", on_delete=models.CASCADE, related_name="contatos")

    def save(self, *args, **kwargs):
        self.contatante = get_current_user()
        super().save(*args, **kwargs)

gestao/templates/alterar_adesao.html
<div class="modal fade" id="alterarAdesaoEnte" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Alterar adesão</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form name="form" id="detalhe_municipio_form" action="{% url 'gestao:alterar_dados_adesao' ente.ente_federado.cod_ibge %}" method="post">
                <div class="modal-body">
                        <div class="card-body">
                        {% csrf_token %}
                        <div class="list-group-item col-md-12">
                            <div class="form-group">
                                <select id="select_situacoes" name="estado_processo" class="form-control">
                                    <option value="1" {% if ente.estado_processo == '0' %}selected{% endif %}>Aguardando preenchimento dos dados cadastrais</option>
                                    <option value="1" {% if ente.estado_processo == '1' %}selected{% endif %}>Aguardando envio da documentação</option>
                                    <option value="2" {% if ente.estado_processo == '2' %}selected{% endif %}>Documentação Recebida - Aguarda Análise</option>
                                    <option value="3" {% if ente.estado_processo == '3' %}selected{% endif %}>Diligência Documental</option>
                                    <option value="4" {% if ente.estado_processo == '4' %}selected{% endif %}>Encaminhado para assinatura do Secretário SAI</option>
                                    <option value="5" {% if ente.estado_processo == '5' %}selected{% endif %}>Aguarda Publicação no DOU</option>
                                    <option value="6" {% if ente.estado_processo == '6' %}selected{% endif %}>Publicado no DOU</option>
                                    </select>
                            </div>

                            <div class="form-group">
                                <textarea id="justificativa_situacao" name="justificativa" class="form-control d-none" style="resize:none" placeholder="Justificativa" rows="4" cols="20">{% if ente.estado_processo == '3' %} {{ ente.justificativa }} {% endif %}</textarea>
                            </div>
                            <div class="form-group">
                                <input type="text" id="data_acordo_situacao" name="data_publicacao_acordo" class="form-control date d-none" value="{% if ente.data_publicacao_acordo %} {{ente.data_publicacao_acordo | date:'SHORT_DATE_FORMAT'}} {% endif %}"
                                    placeholder="Data de Publicação"></input>
                            </div>

                            <div class="form-group">
                                <input type="text" id="localizacao_situacao" name="localizacao" class="form-control d-none" placeholder="Localização"
                                    value="{% if ente.estado_processo == '2' %} {{ente.localizacao}} {% endif %}"></input>
                            </div>


                            <div class="form-group">
                                <input type="text" id="link_acordo_situacao" name="link_publicacao_acordo" class="form-control d-none" placeholder="Link da Publicação" value="{% if ente.link_publicacao_acordo %} {{ ente.link_publicacao_acordo }} {% endif %}"></input>
                            </div>

                            <div class="form-group">
                                <input type="text" id="processo_sei" name="processo_sei" class="form-control" placeholder="Número do Processo SEI" value="{% if ente.processo_sei %} {{ente.processo_sei}} {% endif %}"></input>
                            </div>

                            <div class="form-group">
                                <input type="text" id="data_retificacao_situacao" name="data_publicacao_retificacao" class="form-control date" value="{% if ente.data_publicacao_retificacao %} {{ente.data_publicacao_retificacao | date:'SHORT_DATE_FORMAT'}} {% endif %}" placeholder="Data da Publicação de Retificação (opcional)"></input>
                            </div>

                            <div class="form-group">
                                <input type="text" id="link_retificacao_situacao" name="link_publicacao_retificacao" class="form-control d-none" value="{% if ente.link_publicacao_retificacao %} {{ente.link_publicacao_retificacao}} {% endif %}" placeholder="Link da Publicação de Retificação (opcional)"></input>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-xs" title="Alterar Situação" >Salvar</button>
                    <a href="{% url 'gestao:detalhar' ente.ente_federado.cod_ibge %}" class="btn btn-default btn-xs" value="Cancelar" >Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

gestao/templates/alterar_ente.html
{% extends "gestao/base_gestao.html" %} {% load gestao_tags %} {% block content %} {% load widget_tweaks %}
<div class="row">
	{{form.media}}
	<div class="col-md-12">
		<div class="card">
			<div class="card-header card-header-primary">
				<h4 class="card-title">Editar Ente</h4>
				<p class="card-category">{{object.ente_federado}}</p>
			</div>
			<div class="card-body">
				<form class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}
					<select name="ente_federado" class="form-control d-none"  id="id_ente_federado">
						<option value="{{object.ente_federado.id}}" selected="">{{object.ente_federado}}</option>
					</select>
					{% include "formulario_sistema_gestao.html" %}

					<button type="submit" class="btn btn-primary pull-right">Salvar</button>
					<a class="btn btn-secondary pull-right" href="{% url 'gestao:detalhar' object.ente_federado.cod_ibge %}">Cancelar</a>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

gestao/templates/alterar_plano.html
<div class="modal fade" id="componenteModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Selecione um componente para inserir</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="list-group">
					{% for componente in componentes_restantes %}
						<a
							href="#"
							class="list-group-item list-group-item-action"
							id="{{componente.nome}}"
							onclick="javascript:location.href='{% url 'gestao:inserir_componente' pk=ente.id componente=componente.nome %}'"
							data-dismiss="modal">
								{{componente.descricao}}
						</a>
					{% endfor %}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
			</div>
		</div>
	</div>
</div>

gestao/templates/cadastrador.html
<div class="modal fade" id="cadastradorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cadastradorModalLabel">Alterar Cadastrador</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form method="POST" autocomplete="off" enctype="multipart/form-data" action={% url 'gestao:alterar_cadastrador' object.ente_federado.cod_ibge %}>
					<div class="card-body">
							<div class="form-group">
								<label for="nome-atual">Nome</label>
								<input type="text" class="form-control" id="nome-atual" disabled>
							</div>
							<div class="form-group">
								<label for="cpf-atual">CPF</label>
								<input type="text" class="form-control" id="cpf-atual" disabled>
							</div>
							<div class="form-group">
								<label for="nome-novo" class="col-form-label">Novo Cadastrador</label>
								<input type="text" class="form-control" id="nome-novo" disabled>
							</div>
							<div class="form-group">
								{{form.oficio_cadastrador}}
							</div>
							<div id="cpf_form" class="form-group">
								{% csrf_token %}
								<div class="form-group form-file-upload form-file-multiple">
									<div class="input-group">
										<input type="text" class="form-control" placeholder="Procurar pelo CPF" id="id_cpf_usuario" name="cpf_cadastrador"/>
										<span class="input-group-btn">
											<button type="button" class="btn btn-fab btn-round btn-info" id="search_cpf" onclick="search()">
												<i class="material-icons">search</i>
											</button>
										</span>
									</div>
								</div>
							</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
						<button type="submit" class="btn btn-primary">Alterar Cadastrador</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

gestao/templates/criar_contato.html
{% extends "gestao/base_gestao.html" %}
{% load gestao_tags %}
{% load widget_tweaks %}
{% block content %}
<div class="col-md-12">
  <div class="card">
    <div class="card-header card-header-primary">
      <h4 class="card-title">Registrar Contato</h4>
    </div>
    <div class="card-body">
      <form class="form-horizontal" method="post">{% csrf_token %}
        <div class="col-md-6">
          <div class="form-group">
            <label>Com quem você fez contato?</label>
            {% render_field form.contatado class="form-control" %}
          </div>

          <div class="form-group">
            <label>Qual foi a data do contato?</label>
            {% render_field form.data class="form-control date" %}
          </div>

          <div class="form-group">
            <label>O que foi discutido?</label>
            {% render_field form.discussao class="form-control" %}

            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-10"></div>
              <button type="submit" class="btn btn-primary pull-right">Salvar</button>
              <a class="btn btn-secondary pull-right" href="{% url 'gestao:acompanhar_adesao' %}">Cancelar</a>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

gestao/templates/criar_funcionario.html
{% extends "gestao/base_gestao.html" %} {% load gestao_tags %} {% block content %}

<div class="panel panel-info">
	<div class="panel-body">
		{% include "formulario_funcionario.html" %}
	</div>
</div>

{% endblock content %}

gestao/templates/diligencia.html
{% extends 'gestao/base_gestao.html' %} {% load widget_tweaks %} {% block content %}
<style>
	.lista-diligencia{
		margin-bottom: 2rem;
		border: 1px solid #bec5c5;
		border-radius: 10px;
	}
	.lista-diligencia > li.list-group-item{
		border-bottom: 1px solid #bec5c5;
	}
	.lista-diligencia > li.list-group-item:last-child{
		border-bottom: 0px;
		border-top: 0px;
	}
	table > tbody > tr > td:first-child {
    font-weight: bold;
	}
</style>
<menu data-target="plano" ></menu>
<div class="row">
	<div class="col-md-10">
		<div class="card">
			<div class="card-header card-plain card-header-primary">
				<h4>Diligência</h4>
				<p class="card-category">Envio de diligência para componente do plano de trabalho</p>
			</div>
			<div class="card-body">
				<form method="POST">
				{% csrf_token %}
				<div class="row">
					<div class="col-md-4">
						{% if componente == plano_trabalho  %}
						<table class="table">
							<tr>
								<td>Ente Federado</td>
								<td>{{ sistema_cultura.ente_federado.nome }}</td>
							</tr>
							<tr>
								<td>Criação Sistema</td>
								<td>{{ situacoes.legislacao }}</td>
							</tr>
							<tr>
								<td>Fundo Cultura</td>
								<td>{{ situacoes.fundo_cultura }}</td>
							</tr>
							<tr>
								<td>Conselho Cultural</td>
								<td>{{ situacoes.conselho }}</td>
							</tr>
							<tr>
								<td>Orgao Gestor</td>
								<td>{{ situacoes.orgao_gestor }}</td>
							</tr>
							<tr>
								<td>Plano Cultura</td>
								<td>{{ situacoes.plano }}</td>
							</tr>
						</table>
						{% else %}
						<table class="table">
							<tr>
								<td>Ente Federado</td>
								<td>{{ sistema_cultura.ente_federado.nome }}</td>
							</tr>
							<tr>
								<td>Data de envio do arquivo</td>
								<td>{{ data_envio }}</td>
							</tr>
							<tr>
								<td>Anexo</td>
								<td>
									<a class="btn btn-sm btn-primary" href="{{ arquivo.url }}" target="_blank">
										<i class="material-icons" style="color:white;">save_alt</i>
									</a>
								</td>
							</tr>
							{% if componente != plano_trabalho %}
							<tr>
								<td>Classificação</td>
								<td>
									{% render_field form.classificacao_arquivo class="form-control form-control-sm" %}
								</td>
							</tr>
							{% endif %}
						</table>
						{% endif %}
					</div>
					<div class="col-md-8">
						<div class="row">
								{{form.texto_diligencia}}
								{{form.media}}
						</div>
						<button class="btn btn-primary pull-right" type="submit">Enviar</button>
						<a href="{% url 'gestao:detalhar' cod_ibge=sistema_cultura.ente_federado.cod_ibge %}" class="btn btn-secondary pull-right">Cancelar</a>
					</div>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	{% if historico_diligencias_componentes %}
		<div class="col-md-5">
			<div class="card">
				<div class="card-header card-plain card-header-primary">
					Histórico de Diligências dos Componentes
				</div>
				<div class="card-body">
					{% if componente == plano_trabalho %}
						{% for componente in historico_diligencias_componentes %}
							<div class="col-md-12 lista-diligencia">
								<ul class="list-group"></ul>
								<li class="list-group-item"><b>Componente:</b> {{ componente.get_tipo_display }}</li>
								<li class="list-group-item"><b>Usuário:</b> {{ componente.diligencia.usuario.nome_usuario }}</li>
								<li class="list-group-item"><b>Motivo:</b> {{ componente.diligencia.get_classificacao_arquivo_display }}</li>
								<li class="list-group-item"><b>Data:</b> {{ componente.diligencia.data_criacao }}</li>
								<li class="list-group-item"><b>Resumo:</b> {{ componente.diligencia.texto_diligencia | striptags | safe}}</li>
								</ul>
							</div>
						{% endfor %}
					{% else %}
						{% for componente in historico_diligencias_componentes %}
							{% for diligencia_historica in componente.historico_diligencia %}
								<div class="col-md-12 lista-diligencia">
									<ul class="list-group"></ul>
										<li class="list-group-item"><b>Componente:</b> {{ componente.get_tipo_display }}</li>
										<li class="list-group-item"><b>Usuário:</b> {{ diligencia_historica.usuario.nome_usuario }}</li>
										<li class="list-group-item"><b>Motivo:</b> {{ diligencia_historica.get_classificacao_arquivo_display }}</li>
										<li class="list-group-item"><b>Data:</b> {{ diligencia_historica.data_criacao }}</li>
										<li class="list-group-item"><b>Resumo:</b> {{ diligencia_historica.texto_diligencia | striptags | safe}}</li>
										{% if diligencia_historica.arquivo_url %}
											<li class="list-group-item"><a href="{{ diligencia_historica.arquivo_url }}" target="_blank">Download do Arquivo</a></li>
										{% endif %}
									</ul>
								</div>
							{% empty %}
  							<div class="col-md-12 lista-diligencia">
    							<ul class="list-group"></ul>
      							<li class="list-group-item"><b>Componente:</b> {{ componente.get_tipo_display }}</li>
      							<li class="list-group-item"><b>Usuário:</b> {{ componente.diligencia.usuario.nome_usuario }}</li>
      							<li class="list-group-item"><b>Motivo:</b> {{ componente.diligencia.get_classificacao_arquivo_display }}</li>
      							<li class="list-group-item"><b>Data:</b> {{ componente.diligencia.data_criacao }}</li>
      							<li class="list-group-item"><b>Resumo:</b> {{ componente.diligencia.texto_diligencia | striptags | safe}}</li>
    							</ul>
  							</div>
							{% endfor %}
						{% endfor %}
					{% endif %}
				</div>
			</div>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}